### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by blocknotes** [nebulab/solidus_importer#4]
- [x] Main structure (#1)
  - [x] Base extension using dev_tools
  - [x] Models to store the state of an import / every import rows
  - [x] PORO classes with import logic based on plugins
  - [x] Plugins to check, process and log imported data for: customers, products, orders
  - [x] Plugins configuration via initializer
  - [x] Related specs
- [x] Background processing (#2)
  - [x] Active Job integration
  - [x] Single job to process every row of an import
  - [x] Related specs
- [x] Improve structure to simplify some logics (#9)
- [x] Remove unnecessary code for database_cleaner (#10)
- [x] Image processing (#8)
  - [x] Attach the required images to the row target entity
  - [x] Related specs
- [ ] Improve processors context removing unused keys and using exceptions (#13)
- [ ] Documentation and packaging (#11)
  - [x] README improvements
  - [x] Usage examples (ex. a plugin to notify by email)
  - [x] Gemspec update

**Comment by elia** [comment]
Since the team working on this has now grown into more than one or two people I morphed this issue into the [v1.0](https://github.com/nebulab/solidus_importer/milestone/1) milestone which is supposed to be better for collaboration.
