### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by blocknotes** [nebulab/solidus_importer#5]
- [ ] Release version 1.0 (#4)
- [ ] Improve structure
  - [ ] Replace Paperclip (#6)
- [ ] Improve plugins
  - [ ] Taxon processor (for products)
  - [ ] Options processor (for products)
- [ ] Admin UI (#3)
  - [x] Import listing
  - [x] Import details with import rows
  - [x] Import row details
  - [x] Pagination and filters to improve search functionalities
  - [x] Basic specs (at least load every new route)
- [ ] Improve background processing
  - [ ] Attachment processor: transfer the files in separate jobs
  - [ ] Process rows in the background to improve concurrency
  - [ ] Group the rows by common changes (ex. for products by product slug)
- [ ] Miscellaneous
  - [ ] Be independent from CSV (ex. JSON source)
  - [ ] Tests with Magento
  - [ ] Tests with other solutions

**Comment by elia** [comment]
All the points in this Roadmap have been transferred to issues, appropriately assigned to milestones, and added to the progress board. All of this to match the need for better collaboration tools within a bigger team.
